### PR TITLE
Relations

### PR DESCRIPTION
**Pull request by pagelj**

### CODE REVIEW

**Comment by pagelj** [comment]
I just checked if it is still well formed xml, and there was one issue which is fixed now. Cannot say anything about the validity though.

**Comment by cmil** [comment]
> I just checked if it is still well formed xml, and there was one issue which is fixed now. Cannot say anything about the validity though.

Good catch. Not all the GerDraCor documents pass our schema yet, so validity, for now, is not yet necessary.

**Comment by pagelj** [comment]
Alright! The pull request is also fine from my side then

**Comment by nilsreiter** [comment]
I just added some infos about the relations and their labels to the README file. Can you re-merge?

**Pull request merged**
